### ISSUE TITLE
The epoch during training.

### ISSUE THREAD

**Issue by wensihan** [Justin-Tan/generative-compression#11]
The pre-trained model you give is trained for 50 epochs which defined in the paper.  But I found the default num_epochs is defined as 512 in the config.py, why? And the result I obtained trained for 50 epochs with conditional gan  and without conditional gan both perform not so good.

**Comment by wensihan** [comment]
And, by the way, the code can only run on one gpu? The time of training cost a lot...

**Comment by Justin-Tan** [comment]
Hello, which dataset are you training on, ADE20k? 512 epochs is just a placeholder value. From memory the authors train for 50 epochs on Cityscapes and ADE20k and their results look better than mine on the testing set.
