### ISSUE TITLE
Unable to train the network

### ISSUE THREAD

**Issue by AlverGant** [Justin-Tan/generative-compression#14]
2018-06-26 14:21:25.706113: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at whole_file_read_ops.cc:114 : Not found: data/leftImg8bit/train/tubingen/tubingen_000082_000019_leftImg8bit.png; No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: data/leftImg8bit/train/tubingen/tubingen_000082_000019_leftImg8bit.png; No such file or directory
	 [[Node: ReadFile = ReadFile[](arg0)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,?,?,3]], output_types=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorFromStringHandle)]]

Maybe there are training files missing?

Command issued was ~/generative-compression$ python3 train.py -opt momentum --name my_network

Installation script used was: on ubuntu 14.04 server 64 bits
# update OS
sudo apt update && sudo apt upgrade

# Prerequisites
sudo apt-get install python3-pip python3-dev pkg-config \
libfreetype6-dev gfortran libopenblas-dev python3-tables
sudo pip3 install -U setuptools
sudo pip3 install matplotlib
pip3 install numpy pandas
sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.8.0-cp34-cp34m-linux_x86_64.whl

# Compile OpenBLAS
cd "$HOME" && git clone https://github.com/xianyi/OpenBLAS.git
cd OpenBLAS
git pull
make FC=gfortran -j $(($(nproc) + 1))
sudo make PREFIX=/usr/local install

sudo pip3 install seaborn

git clone https://github.com/Justin-Tan/generative-compression.git
cd generative-compression
python3 train.py -opt momentum --name my_network
python3 compress.py -r /path/to/model/checkpoint -i /path/to/image -o path/to/output/image

**Comment by Justin-Tan** [comment]
You need to download the respective datasets before starting training, see the Data/Setup section in the readme. Under the data directory there are sample `.h5` files for the cityscapes dataset and a script for resizing the raw cityscapes leftimg8bit images.

**Comment by zhiqiang-zhu** [comment]
Hello, are you address the problem? And which datasets you download ?

**Comment by Justin-Tan** [comment]
Read the data/setup section under the readme, it is explained in depth there.
