### ISSUE TITLE
How to uncompress the result?

### ISSUE THREAD

**Issue by chhss17** [Justin-Tan/generative-compression#21]
As the title says,how can I uncompress the result of compress.py

**Comment by Justin-Tan** [comment]
The returned image is the uncompressed image. Compression refers to the projection on a lower dimensional vector embedding that is quantized around a set of centers. This can be stored and uncompressed through the decoder at a later stage, which requires you to save the parameters of the decoder on disk somewhere, so you would only save memory if you had a large amount of images you wanted to compress/decompress.
