### ISSUE TITLE
Two issues about the dataset to train the model

### ISSUE THREAD

**Issue by myaolee** [Justin-Tan/generative-compression#36]
Hi Justin-Tan, Can i get your attention？ Firstly, thank you for sharing your work with us. Now I have two issues about this project.
1、For your pertrained models，is only the Cityscapes leftImg8bit dataset used to train the models?  But in the "Data/Set up"part , it is said that"Training was done using the ADE 20k dataset and the Cityscapes leftImg8bit dataset".   So I couldn't know exactly what you mean.  Do you mean that the ADE 20k dataset is used to train the global model? And then based on this model, the Cityscapes leftImg8bit dataset and the gtFine dataset for the corresponding semantic maps are used to train the conditional  GAN model?
2、Are there  noise concatenated to the quantized image representation  in the conditional GAN model? Does only the global model need noise to concat with the the quantized image representation, but the conditional model(ie.,the model need semantic map) does not need the noise? Or whether any model can connect noise to the quantized image representation?

I would appreciate it, if you could help me answer the above question.

**Comment by Justin-Tan** [comment]
1. I used two separate models to train the model, there are two different models, from memory.

2. Right now there is just noise sampled from a Gaussian distribution combined with the quantized portion, I haven't tried it with the conditional model but doing so should be straightforward, as in, I don't see any reason why *not* to do it.

**Comment by myaolee** [comment]
Ok, i got it. Thanks for your reply again.
