### ISSUE TITLE
Train.py execution failure, system crash

### ISSUE THREAD

**Issue by onlyraly** [Justin-Tan/generative-compression#9]
In train.py, while True has been executed and there is no exit statement. Can you add instructions in this part?

**Comment by Justin-Tan** [comment]
Can you post the full error message?

**Comment by Justin-Tan** [comment]
The exit condition is when Tensorflow's Dataset iterator reaches the end of epoch, it will throw an error which will be caught. Then summary statistics will be computed and printed.
